name: Flutter Android Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'  # You can adjust this to your Flutter version

      # 3. Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # 5. Upload APK artifact
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
