name: Android-apk-build

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🤖 Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Rename output
        run: |
          mkdir -p build/app/outputs/release
          cp build/app/outputs/flutter-apk/app-release.apk build/app/outputs/release/FlutterApkExport.apk

      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/release/FlutterApkExport.apk
          tag: v1.0
          overwrite: true
          body: "This is the first Android release"
